language: nodejs

before_script:
  - npm run setup
  - npm run build

script:
  - npm run test

after_success:
  - npm pack

deploy:
  - provider: npm
    skip_cleanup: true
    email: "ste.staub@gmail.com"
    api_key: $NPM_TOKEN
    on:
      tags: true